[build.environment]
  NODE_VERSION = "18"
  # don't need playwright for docs build
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[build]
  publish = ".vitepress/dist"
  command = "pnpm run build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- ./package.json pnpm-lock.yaml"

[[redirects]]
  from = "/new"
  to = "https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/basic?initialPath=__vitest__/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
