[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = ".vitepress/dist"
  command = "pnpm run build"

#[[redirects]]
  #from = "https://vitest-docs-pt.netlify.app/*"
  #to = "https://pt.vitest.dev/:splat"
  #status = 301
  #force = true

[[redirects]]
  from = "/new"
  to = "https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/basic?initialPath=__vitest__"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
