name: Benchmark

on:
  issue_comment:
    types:
      - created

jobs:
  bench:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && (github.event.comment.body == '/bench' || github.event.comment.body == '/benchmark') }}

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - name: Install
        working-directory: ./bench
        run: pnpm i

      - name: Run benchmark
        working-directory: ./bench
        run: pnpm bench:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
